spring.application.name=SIVA

# Configuracao Dinamica do Banco de Dados
# O Spring vai ler o Aiven (no Render). Se nao achar as variaveis, roda no Docker local.
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/ipem_db?createDatabaseIfNotExist=true&connectTimeout=30000}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuracoes do Flyway e JPA
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/mysql
spring.flyway.validate-on-migrate=false
spring.flyway.repair-on-migrate=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguranca (JWT)
api.security.token.secret=${JWT_SECRET:3f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0}

# Upload Limits
# Configurações de E-mail (Variáveis de Ambiente)
spring.mail.host=${MAIL_HOST:smtp-mail.outlook.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:bifrost-connect@hotmail.com}
spring.mail.password=${MAIL_PASSWORD:bhnpvngizskudclr}

#czgdprmosmsvrpjr
#bhnpvngizskudclr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB