spring.application.name=SIVA

# Configuracao do H2 (Modo de Compatibilidade com MySQL)
spring.datasource.url=jdbc:h2:mem:ipem_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=YEAR
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Configuracoes do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuracoes do Flyway e JPA
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=false

# Inicialização de dados via sql.init desabilitada (Flyway fara o trabalho)
spring.sql.init.mode=never

# Seguranca (JWT)
api.security.token.secret=fallback_h2_secret_key_to_run_locally_without_docker
